### ISSUE TITLE
codegen from palette json

### ISSUE THREAD

**Issue by backwardspy** [catppuccin/python#2]
rather than writing all the colours out by hand we should have a way to generate the relevant python code automatically using the latest palette json.

**Comment by nekowinston** [comment]
Just saw this issue again, I've just (finally!) updated the palette JSON to that more detailed format we talked about a while ago: https://github.com/catppuccin/palette/blob/v1.0.1/palette.json

**Comment by backwardspy** [comment]
lovely stuff, thanks for the update. i shall roll this into the next version and get rid of the custom hsla methods i added!
