### ISSUE TITLE
Inconsistent colors with nvim configuration

### ISSUE THREAD

**Issue by raffaem** [catppuccin/python#24]
I have both the [nvim](https://github.com/catppuccin/nvim) theme and this theme for IPython.

However, colors are inconsistent.

For example, "from" and "import" keywords are mauve in nvim and teal in IPython.

Package names are white in nvim and orange in IPython.

Imported classes are yellow and peach respectively:

![image](https://github.com/catppuccin/python/assets/54762742/e125552d-ffaa-4163-b1aa-fdb44a84dcf8)

**Comment by backwardspy** [comment]
you're right, the current colour choices in the pygments integration are from before we had standardised our syntax highlights; they need to be changed to fit the updated style guide.

**Comment by raffaem** [comment]
https://github.com/catppuccin/python/blob/bbe9c172e80bbedf375a4647057c6a0c59d1f22a/catppuccin/extras/pygments.py#L26

https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md#code-editors

?

**Comment by 10b14224cc** [comment]
I'm trying to have a shot at it but that's not gonna work.

Everything seems to be rendered with `Name`: packages, objects, variables, functions.

For example I expected functions to be rendered with `Name.Function`.

**Comment by backwardspy** [comment]
i found it very hard to find documentation on how exactly to write proper pygments themes, especially when it comes to their use in ipython. what we have right now is the result of a lot of experimentation and referencing what scant resources i could find on github et cetera. please let me know if you do manage to make any headway with it!

**Comment by raffaem** [comment]
> (in reply to a deleted comment) i found it very hard to find documentation on how exactly to write proper pygments themes, especially when it comes to their use in ipython. what we have right now is the result of a lot of experimentation and referencing what scant resources i could find on github et cetera. please let me know if you do manage to make any headway with it!

Does the PR looks good?

I find Pygments is a "simpler" syntax highlighter. The lexer splits code into tokens, the filter filters the list of tokens, then the formatter will print out the list of tokens using the style. 

This is different from the syntax highlighting that neovim uses which is based on tree-sitter.

Pygments doesn't distinguish between variables, global functions, class functions. All of them are tokenized as `Token.Name`, so it leads to different syntax highlighting.

Anyway, I think I came near to the best we could.

**Comment by backwardspy** [comment]
hey, i saw your PR but haven't had a chance to try it out yet, but i really appreciate the effort you've put into this. i'll try and give it a go soon and give you some feedback. thanks!
