### ISSUE TITLE
Suggestion: Add actual colors when printing the color

### ISSUE THREAD

**Issue by Groovin-Dev** [catppuccin/python#3]
If we were to add a string property to the `Color` class, it would make for some really nice printing.

Adding this:
```py
def __repr__(self) -> str:
    return f"\x1b[48;2;{self.red};{self.green};{self.blue}m {self.hex} \x1b[0m"
```

Results in this:
![image](https://user-images.githubusercontent.com/56172528/199081051-94b14470-741e-46f3-b68b-e393e06aba77.png)

And while it is not necessary, I think it would be nice to have

**Comment by backwardspy** [comment]
not a bad concept, i'll play around with some options for this. thanks for the suggestion!

**Comment by backwardspy** [comment]
we've opted to integrate with `rich` to support coloured printing instead of a custom solution. thanks for the suggestion!
