### ISSUE TITLE
Suggestion: Add terminal printing support

### ISSUE THREAD

**Issue by Groovin-Dev** [catppuccin/python#4]
Not 100% what to call it but if we extend the color class with an `add` method, it would allow users to do something like
```py
def __add__(self, other: str) -> str:
    return f"\033[38;2;{self.red};{self.green};{self.blue}m{other}\033[0m"
```

```py
flavour = Flavour.latte()
print(flavour.flamingo + "This is a test")
```

![image](https://user-images.githubusercontent.com/56172528/199098275-dee0a1ee-de67-4df3-bd69-6a834c683403.png)

Kind of similar to https://github.com/catppuccin/python/issues/3

**Comment by backwardspy** [comment]
i am planning a few integrations of this palette with other libraries, at least one of which would allow for terminal string colouring. i haven't looked into all the specifics of this yet, but it's definitely something i want!

i will ping you on this issue when i've got more to show.

**Comment by Mylus1** [comment]
I have been able to get this working with the Rich library. Using the console import we can manually choose the theme we want and the colour then associated with it. 
I've added it all into the PR and left some of the example use code in there for testing, I'm not sure if you wanted to keep it there or wanted to test it out yourself to see if it's up to scratch @Groovin-Dev @backwardspy

**Comment by backwardspy** [comment]
we've opted to integrate with `rich` to support coloured printing instead of a custom solution. thanks for the suggestion!
