### ISSUE TITLE
matplotlib invalid package style

### ISSUE THREAD

**Issue by paw-lu** [catppuccin/python#93]
Running the example in the README

```pytb
OSError: 'mocha' is not a valid package style, path of style file, URL of style file, or library style name (library styles are listed in `style.available`)
```

```python
import catppuccin
import matplotlib as mpl
import matplotlib.pyplot as plt

mpl.style.use(catppuccin.PALETTE.mocha.identifier)
plt.plot([0, 1, 2, 3], [1, 2, 3, 4])
plt.show()

```

---

thanks for all the work here!

**Comment by paw-lu** [comment]
realized i'm on 2.2.0. i'm guessing after that support for 3.8 was dropped. going to close! thanks!

**Comment by backwardspy** [comment]
the merge of catppuccin/matplotlib into this library happened in [v2.3.0](https://github.com/catppuccin/python/releases/tag/v2.3.0). did you manage to get it working?

**Comment by paw-lu** [comment]
> did you manage to get it working?

nah, cause i'm stuck on 3.8 for other reasons, so I won't be able to upgrade. but this is my problem! sorry for noise here—should have checked version before 😅

**Comment by backwardspy** [comment]
no worries! we still support 3.8, despite it going end-of-life recently. i'm not sure why this wouldn't be working for you, i'll investigate it in more depth later and see what i can find.

**Comment by backwardspy** [comment]
ah, it looks like the matplotlib version we depend on has unfortunately dropped support for python 3.8, so by extension we have too. generally we follow [python's supported versions](https://devguide.python.org/versions) so i'm going to leave this as-is for now.

sorry i couldn't do more!

**Comment by paw-lu** [comment]
nothing to be sorry about! completely understand dropping 3.8 support!
